# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-13 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasdremote', '0002_auto_20180130_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagefile',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
