# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackageFileError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('stage', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('retry_delay', models.IntegerField(default=2)),
                ('package_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='dasdapi.PackageFile')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(max_length=255)),
                ('package_files_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TorrentError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('stage', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('retry_delay', models.IntegerField(default=2)),
                ('torrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='dasdapi.Torrent')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
        migrations.AddField(
            model_name='packagefile',
            name='torrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_file_set', to='dasdapi.Torrent'),
        ),
    ]
